Revert "Switch fs_mgr and adb to libcrypto_utils."
This reverts commit f3c2f1b9f5bc7eb68c8b21d190995ec6d6bf1f30.

We need to revert this because it breaks the build:

In file included from system/core/fs_mgr/fs_mgr_verity.cpp:43:
In file included from system/extras/libfec/include/fec/io.h:27:
system/core/include/mincrypt/rsa.h:48:5: error: conflicting types for 'RSA_verify'
int RSA_verify(const RSAPublicKey *key,
    ^
external/boringssl/src/include/openssl/rsa.h:218:20: note: previous declaration is here
OPENSSL_EXPORT int RSA_verify(int hash_nid, const uint8_t *msg, size_t msg_len,
                   ^
1 error generated.